spring:
  datasource:
    url: jdbc:postgresql://javatesting-erzatnis-6188.aivencloud.com:12716/websocket
    username: avnadmin
    password: AVNS_VC2ImMu0_wGLRAa3H7i
  jpa:
    hibernate:
      ddl-auto: create-drop
